spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka server 의 URL 지정
service:
  jwt:
    access-expiration: 3600000
    secret-key: ${SECRET_KEY}

server:
  port: 19095